### ISSUE TITLE
Why no GitHub code hmm

### ISSUE THREAD

**Issue by IAFahim** [BushraOnika/Onika-s-Ice-cream-parlour#1]
See had to come and give boka, you aren't coding for 2 months. Code code, no need to say thanks. Me know me good boy huh.

**Comment by IAFahim** [comment]
Where did your repo go, it was a cute profile repo naa

**Comment by BushraOnika** [comment]
> Where did your repo go, it was a cute profile repo naa

That was created by mistake didn't knew 😑
And you shouldn't look what I'm doing or not goo

**Comment by IAFahim** [comment]
Who said I shouldn't look at what you are doing, hmm. Or how would I know what you Upto. Sleep sleep.

**Comment by BushraOnika** [comment]
Don't sleep to early changed daily life routines btw

**Comment by IAFahim** [comment]
Yes yes, me remember you had friends that needed tutoring late late also. You keep up late for any reason now? Like job, or study, or learning?

**Comment by IAFahim** [comment]
Wait ehh, again asking you questions huh you would kill me then I will be all dead. You don't have to hide what you are doing you know, and if you feel like I check your GitHub account too much you can say. Me would check little only, you just need be bestest naa.

**Comment by IAFahim** [comment]
Ow no me get sad sad again ehh, won't talk with you huh. See came to give boka and did. Task done. You you rest kintu.

**Comment by BushraOnika** [comment]
I was never the bestest and don't want to be anymore anyways 
And my thinking they are not for you anyways you can do whatever you want you know I don't think about you

**Comment by IAFahim** [comment]
Tata you, I need to have better rules not to disturb you, oh yes yes. Wait me block you in GitHub too. That way won't think of you when in GitHub.
And I got your no thinking about you text, yes baba yes why would you even think about me in first place. But you would be bestest even if you don't try. And always you are huh. Thank you for replying, nice person.
